/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmapp;

import java.awt.Color;

/**
 *
 * @author 05den
 */
public class AddNewAnimal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewAnimal.class.getName());

    /**
     * Creates new form AddNewAnimal
     */
    public AddNewAnimal() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAnimalBtnGroup = new javax.swing.ButtonGroup();
        cowImage = new javax.swing.JLabel();
        chickenImage = new javax.swing.JLabel();
        lambImage = new javax.swing.JLabel();
        backAmBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        cowRB = new javax.swing.JRadioButton();
        chickenRB = new javax.swing.JRadioButton();
        lambRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cowImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/cow.png"))); // NOI18N

        chickenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/chicken.png"))); // NOI18N

        lambImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/lamb.png"))); // NOI18N

        backAmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/backButton.png"))); // NOI18N
        backAmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAmBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        title.setText("Choose an Animal you'd wish to add to the farm");

        addAnimalBtnGroup.add(cowRB);
        cowRB.setText("Cow");

        addAnimalBtnGroup.add(chickenRB);
        chickenRB.setText("Chicken");
        chickenRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenRBActionPerformed(evt);
            }
        });

        addAnimalBtnGroup.add(lambRB);
        lambRB.setText("Lamb");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cowImage)
                            .addComponent(chickenImage)
                            .addComponent(lambImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cowRB))
                                .addComponent(chickenRB))
                            .addComponent(lambRB, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cowRB)
                        .addGap(61, 61, 61)
                        .addComponent(chickenRB)
                        .addGap(59, 59, 59)
                        .addComponent(lambRB)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cowImage)
                        .addGap(34, 34, 34)
                        .addComponent(chickenImage)
                        .addGap(32, 32, 32)
                        .addComponent(lambImage)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backAmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAmBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backAmBtnActionPerformed

    private void chickenRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewAnimal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup addAnimalBtnGroup;
    private javax.swing.JButton backAmBtn;
    private javax.swing.JLabel chickenImage;
    private javax.swing.JRadioButton chickenRB;
    private javax.swing.JLabel cowImage;
    private javax.swing.JRadioButton cowRB;
    private javax.swing.JLabel lambImage;
    private javax.swing.JRadioButton lambRB;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
