/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmapp;

import java.awt.Color;

/**
 *
 * @author 05den
 */
public class AddNewAnimal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewAnimal.class.getName());

    /**
     * Creates new form AddNewAnimal
     */
    public AddNewAnimal() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAnimalBtnGroup = new javax.swing.ButtonGroup();
        cowImage = new javax.swing.JLabel();
        chickenImage = new javax.swing.JLabel();
        lambImage = new javax.swing.JLabel();
        backAmBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        cowRB = new javax.swing.JRadioButton();
        chickenRB = new javax.swing.JRadioButton();
        lambRB = new javax.swing.JRadioButton();
        idLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        isAliveLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        IsHealthyLbl = new javax.swing.JLabel();
        isMilkingLbl = new javax.swing.JLabel();
        litProdLbl = new javax.swing.JLabel();
        isPregnantLbl = new javax.swing.JLabel();
        eggQtyLbl = new javax.swing.JLabel();
        eggQualityLbl = new javax.swing.JLabel();
        isLayingEggsLbl = new javax.swing.JLabel();
        woolLengthLbl = new javax.swing.JLabel();
        isLeanedLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cowImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/cow.png"))); // NOI18N

        chickenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/chicken.png"))); // NOI18N

        lambImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/lamb.png"))); // NOI18N

        backAmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/backButton.png"))); // NOI18N
        backAmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAmBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        title.setText("Choose an Animal you'd wish to add to the farm");

        addAnimalBtnGroup.add(cowRB);
        cowRB.setText("Cow");

        addAnimalBtnGroup.add(chickenRB);
        chickenRB.setText("Chicken");
        chickenRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenRBActionPerformed(evt);
            }
        });

        addAnimalBtnGroup.add(lambRB);
        lambRB.setText("Lamb");

        idLbl.setText("ID");

        genderLbl.setText("Gender");

        ageLbl.setText("Age");

        isAliveLbl.setText("Alive");

        weightLbl.setText("Weight");

        IsHealthyLbl.setText("Healthy");

        isMilkingLbl.setText("isMilking");

        litProdLbl.setText("Litres Produced");

        isPregnantLbl.setText("Pregnant");

        eggQtyLbl.setText("Egg Quantity");

        eggQualityLbl.setText("Egg Quality");

        isLayingEggsLbl.setText("Laying Eggs");

        woolLengthLbl.setText("Wool Length");

        isLeanedLbl.setText("Leaned");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(litProdLbl)
                                .addGap(156, 156, 156))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(isMilkingLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(isPregnantLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idLbl)
                                        .addComponent(genderLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(weightLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(IsHealthyLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ageLbl)
                                        .addComponent(isAliveLbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eggQtyLbl)
                                    .addComponent(eggQualityLbl)
                                    .addComponent(isLayingEggsLbl)
                                    .addComponent(woolLengthLbl)
                                    .addComponent(isLeanedLbl))
                                .addGap(53, 53, 53)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cowImage)
                    .addComponent(chickenImage)
                    .addComponent(lambImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chickenRB)
                    .addComponent(lambRB)
                    .addComponent(cowRB))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genderLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ageLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isAliveLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(weightLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IsHealthyLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isMilkingLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(litProdLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isPregnantLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cowImage)
                                                .addGap(34, 34, 34)
                                                .addComponent(chickenImage))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(eggQtyLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eggQualityLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(isLayingEggsLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(woolLengthLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(isLeanedLbl)))
                                        .addGap(32, 32, 32)
                                        .addComponent(lambImage))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(cowRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenRB)
                                .addGap(59, 59, 59)
                                .addComponent(lambRB)
                                .addGap(19, 19, 19)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backAmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAmBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backAmBtnActionPerformed

    private void chickenRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewAnimal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IsHealthyLbl;
    private javax.swing.ButtonGroup addAnimalBtnGroup;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JButton backAmBtn;
    private javax.swing.JLabel chickenImage;
    private javax.swing.JRadioButton chickenRB;
    private javax.swing.JLabel cowImage;
    private javax.swing.JRadioButton cowRB;
    private javax.swing.JLabel eggQtyLbl;
    private javax.swing.JLabel eggQualityLbl;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel isAliveLbl;
    private javax.swing.JLabel isLayingEggsLbl;
    private javax.swing.JLabel isLeanedLbl;
    private javax.swing.JLabel isMilkingLbl;
    private javax.swing.JLabel isPregnantLbl;
    private javax.swing.JLabel lambImage;
    private javax.swing.JRadioButton lambRB;
    private javax.swing.JLabel litProdLbl;
    private javax.swing.JLabel title;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JLabel woolLengthLbl;
    // End of variables declaration//GEN-END:variables
}
