/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmapp;

import java.awt.Color;

/**
 *
 * @author 05den
 */
public class AddNewAnimal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewAnimal.class.getName());

    /**
     * Creates new form AddNewAnimal
     */
    public AddNewAnimal() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAnimalBtnGroup = new javax.swing.ButtonGroup();
        genderBG = new javax.swing.ButtonGroup();
        aliveBG = new javax.swing.ButtonGroup();
        healthyBG = new javax.swing.ButtonGroup();
        milkingBG = new javax.swing.ButtonGroup();
        pregnantBG = new javax.swing.ButtonGroup();
        layEggsBG = new javax.swing.ButtonGroup();
        leanedBG = new javax.swing.ButtonGroup();
        cowImage = new javax.swing.JLabel();
        chickenImage = new javax.swing.JLabel();
        lambImage = new javax.swing.JLabel();
        backAmBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        cowRB = new javax.swing.JRadioButton();
        chickenRB = new javax.swing.JRadioButton();
        lambRB = new javax.swing.JRadioButton();
        idLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        isAliveLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        IsHealthyLbl = new javax.swing.JLabel();
        isMilkingLbl = new javax.swing.JLabel();
        litProdLbl = new javax.swing.JLabel();
        isPregnantLbl = new javax.swing.JLabel();
        eggQtyLbl = new javax.swing.JLabel();
        eggQualityLbl = new javax.swing.JLabel();
        isLayingEggsLbl = new javax.swing.JLabel();
        woolLengthLbl = new javax.swing.JLabel();
        isLeanedLbl = new javax.swing.JLabel();
        aliveYesRB = new javax.swing.JRadioButton();
        aliveNoRB = new javax.swing.JRadioButton();
        healthyNoRB = new javax.swing.JRadioButton();
        healthyYesRB = new javax.swing.JRadioButton();
        pregNoRB = new javax.swing.JRadioButton();
        pregYesRB = new javax.swing.JRadioButton();
        idTF = new javax.swing.JTextField();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        ageTF = new javax.swing.JTextField();
        weightTF = new javax.swing.JTextField();
        milkYesRB = new javax.swing.JRadioButton();
        milkNoRB = new javax.swing.JRadioButton();
        litresTF = new javax.swing.JTextField();
        eggQtyTF = new javax.swing.JTextField();
        eggQualTF = new javax.swing.JTextField();
        layEggsYesRB = new javax.swing.JRadioButton();
        layEggsNoRB = new javax.swing.JRadioButton();
        woolLenTF = new javax.swing.JTextField();
        leanedYesRB = new javax.swing.JRadioButton();
        leanedNoRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cowImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/cow.png"))); // NOI18N

        chickenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/chicken.png"))); // NOI18N

        lambImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/lamb.png"))); // NOI18N

        backAmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAmBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        title.setText("Choose an Animal you'd wish to add to the farm");

        cowRB.setBackground(new java.awt.Color(254, 220, 159));
        addAnimalBtnGroup.add(cowRB);
        cowRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cowRB.setText("Cow");
        cowRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cowRBActionPerformed(evt);
            }
        });

        chickenRB.setBackground(new java.awt.Color(254, 220, 159));
        addAnimalBtnGroup.add(chickenRB);
        chickenRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chickenRB.setText("Chicken");
        chickenRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenRBActionPerformed(evt);
            }
        });

        lambRB.setBackground(new java.awt.Color(254, 220, 159));
        addAnimalBtnGroup.add(lambRB);
        lambRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lambRB.setText("Lamb");
        lambRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambRBActionPerformed(evt);
            }
        });

        idLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idLbl.setText("ID");

        genderLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLbl.setText("Gender");

        ageLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageLbl.setText("Age");

        isAliveLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isAliveLbl.setText("Alive");

        weightLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        weightLbl.setText("Weight");

        IsHealthyLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IsHealthyLbl.setText("Healthy");

        isMilkingLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isMilkingLbl.setText("isMilking");

        litProdLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        litProdLbl.setText("Litres Produced");

        isPregnantLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isPregnantLbl.setText("Pregnant");

        eggQtyLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eggQtyLbl.setText("Egg Quantity");

        eggQualityLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eggQualityLbl.setText("Egg Quality");

        isLayingEggsLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isLayingEggsLbl.setText("Laying Eggs");

        woolLengthLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        woolLengthLbl.setText("Wool Length");

        isLeanedLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isLeanedLbl.setText("Leaned");

        aliveYesRB.setBackground(new java.awt.Color(254, 220, 159));
        aliveBG.add(aliveYesRB);
        aliveYesRB.setText("Yes");

        aliveNoRB.setBackground(new java.awt.Color(254, 220, 159));
        aliveBG.add(aliveNoRB);
        aliveNoRB.setText("No");

        healthyNoRB.setBackground(new java.awt.Color(254, 220, 159));
        healthyBG.add(healthyNoRB);
        healthyNoRB.setText("No");

        healthyYesRB.setBackground(new java.awt.Color(254, 220, 159));
        healthyBG.add(healthyYesRB);
        healthyYesRB.setText("Yes");

        pregNoRB.setBackground(new java.awt.Color(254, 220, 159));
        pregnantBG.add(pregNoRB);
        pregNoRB.setText("No");

        pregYesRB.setBackground(new java.awt.Color(254, 220, 159));
        pregnantBG.add(pregYesRB);
        pregYesRB.setText("Yes");
        pregYesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregYesRBActionPerformed(evt);
            }
        });

        idTF.setBackground(new java.awt.Color(255, 255, 255));
        idTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        idTF.setText("i.e ....");
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        maleRB.setBackground(new java.awt.Color(254, 220, 159));
        genderBG.add(maleRB);
        maleRB.setText("M");
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });

        femaleRB.setBackground(new java.awt.Color(254, 220, 159));
        genderBG.add(femaleRB);
        femaleRB.setText("F");

        ageTF.setBackground(new java.awt.Color(255, 255, 255));
        ageTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ageTF.setText("i.e ...");

        weightTF.setBackground(new java.awt.Color(255, 255, 255));
        weightTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        weightTF.setText("i.e ....");

        milkYesRB.setBackground(new java.awt.Color(254, 220, 159));
        milkingBG.add(milkYesRB);
        milkYesRB.setText("Yes");

        milkNoRB.setBackground(new java.awt.Color(254, 220, 159));
        milkingBG.add(milkNoRB);
        milkNoRB.setText("No");

        litresTF.setBackground(new java.awt.Color(255, 255, 255));
        litresTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        litresTF.setText("i.e ....");

        eggQtyTF.setBackground(new java.awt.Color(255, 255, 255));
        eggQtyTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eggQtyTF.setText("jTextField2");

        eggQualTF.setBackground(new java.awt.Color(255, 255, 255));
        eggQualTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eggQualTF.setText("(1-5)");
        eggQualTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggQualTFActionPerformed(evt);
            }
        });

        layEggsYesRB.setBackground(new java.awt.Color(254, 220, 159));
        layEggsBG.add(layEggsYesRB);
        layEggsYesRB.setText("Yes");
        layEggsYesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layEggsYesRBActionPerformed(evt);
            }
        });

        layEggsNoRB.setBackground(new java.awt.Color(254, 220, 159));
        layEggsBG.add(layEggsNoRB);
        layEggsNoRB.setText("No");

        woolLenTF.setBackground(new java.awt.Color(255, 255, 255));
        woolLenTF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        woolLenTF.setText("i.e ....");
        woolLenTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woolLenTFActionPerformed(evt);
            }
        });

        leanedYesRB.setBackground(new java.awt.Color(254, 220, 159));
        leanedBG.add(leanedYesRB);
        leanedYesRB.setText("Yes");
        leanedYesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leanedYesRBActionPerformed(evt);
            }
        });

        leanedNoRB.setBackground(new java.awt.Color(254, 220, 159));
        leanedBG.add(leanedNoRB);
        leanedNoRB.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(isPregnantLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(pregYesRB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pregNoRB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(litProdLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(litresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(idLbl)
                                                    .addComponent(genderLbl)
                                                    .addComponent(ageLbl)
                                                    .addComponent(isAliveLbl)
                                                    .addComponent(weightLbl)
                                                    .addComponent(IsHealthyLbl)
                                                    .addComponent(isMilkingLbl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(healthyYesRB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(healthyNoRB))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(milkYesRB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(milkNoRB))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(aliveYesRB)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(aliveNoRB))
                                                            .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(maleRB)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(femaleRB))
                                                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(isLayingEggsLbl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(layEggsYesRB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(layEggsNoRB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(woolLengthLbl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(woolLenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(isLeanedLbl)
                                                                .addGap(37, 37, 37)
                                                                .addComponent(leanedYesRB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(leanedNoRB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                    .addComponent(eggQualityLbl)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(eggQualTF))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                    .addComponent(eggQtyLbl)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(eggQtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cowImage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cowRB)
                                                .addGap(21, 21, 21))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chickenImage)
                                                    .addComponent(lambImage))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chickenRB)
                                                    .addComponent(lambRB)))))))
                            .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eggQtyLbl)
                                    .addComponent(eggQtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eggQualityLbl)
                                    .addComponent(eggQualTF, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isLayingEggsLbl)
                                    .addComponent(layEggsYesRB)
                                    .addComponent(layEggsNoRB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(woolLengthLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(woolLenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isLeanedLbl)
                                    .addComponent(leanedYesRB)
                                    .addComponent(leanedNoRB)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cowImage)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(cowRB)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chickenImage)
                                        .addGap(32, 32, 32)
                                        .addComponent(lambImage))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(chickenRB)
                                        .addGap(59, 59, 59)
                                        .addComponent(lambRB)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLbl)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLbl)
                            .addComponent(maleRB)
                            .addComponent(femaleRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isAliveLbl)
                            .addComponent(aliveYesRB)
                            .addComponent(aliveNoRB))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IsHealthyLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isMilkingLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(healthyYesRB)
                                    .addComponent(healthyNoRB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(milkYesRB)
                                    .addComponent(milkNoRB))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(litProdLbl)
                            .addComponent(litresTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isPregnantLbl)
                            .addComponent(pregYesRB)
                            .addComponent(pregNoRB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backAmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAmBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backAmBtnActionPerformed

    private void chickenRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenRBActionPerformed
    // enable CHICKEN components
    eggQtyLbl.setEnabled(true);
    eggQtyTF.setEnabled(true);
    eggQualityLbl.setEnabled(true);
    eggQualTF.setEnabled(true);
    isLayingEggsLbl.setEnabled(true);
    layEggsYesRB.setEnabled(true);
    layEggsNoRB.setEnabled(true);

    // disable LAMB components
    woolLengthLbl.setEnabled(false);
    woolLenTF.setEnabled(false);
    isLeanedLbl.setEnabled(false);
    leanedYesRB.setEnabled(false);
    leanedNoRB.setEnabled(false);

    // disable COW components
    milkYesRB.setEnabled(false);
    milkNoRB.setEnabled(false);
    isMilkingLbl.setEnabled(false);
    litProdLbl.setEnabled(false);
    litresTF.setEnabled(false);
    isPregnantLbl.setEnabled(false);
    pregYesRB.setEnabled(false);
    pregNoRB.setEnabled(false);
    isMilkingLbl.setEnabled(false);
    }//GEN-LAST:event_chickenRBActionPerformed

    private void pregYesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregYesRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregYesRBActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBActionPerformed

    private void eggQualTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggQualTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eggQualTFActionPerformed

    private void layEggsYesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layEggsYesRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layEggsYesRBActionPerformed

    private void woolLenTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woolLenTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_woolLenTFActionPerformed

    private void leanedYesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leanedYesRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leanedYesRBActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void cowRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cowRBActionPerformed
        
    // disable CHICKEN components
    eggQtyLbl.setEnabled(false);
    eggQtyTF.setEnabled(false);
    eggQualityLbl.setEnabled(false);
    eggQualTF.setEnabled(false);
    isLayingEggsLbl.setEnabled(false);
    layEggsYesRB.setEnabled(false);
    layEggsNoRB.setEnabled(false);

    // disable LAMB components
    woolLengthLbl.setEnabled(false);
    woolLenTF.setEnabled(false);
    isLeanedLbl.setEnabled(false);
    leanedYesRB.setEnabled(false);
    leanedNoRB.setEnabled(false);

    // enable COW components
    milkYesRB.setEnabled(true);
    milkNoRB.setEnabled(true);
    isMilkingLbl.setEnabled(true);
    litProdLbl.setEnabled(true);
    litresTF.setEnabled(true);
    pregYesRB.setEnabled(true);
    pregNoRB.setEnabled(true);
    isPregnantLbl.setEnabled(true);
    isMilkingLbl.setEnabled(true);

    }//GEN-LAST:event_cowRBActionPerformed

    private void lambRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambRBActionPerformed
        // disable CHICKEN components
    eggQtyLbl.setEnabled(false);
    eggQtyTF.setEnabled(false);
    eggQualityLbl.setEnabled(false);
    eggQualTF.setEnabled(false);
    isLayingEggsLbl.setEnabled(false);
    layEggsYesRB.setEnabled(false);
    layEggsNoRB.setEnabled(false);

    // enable LAMB components
    woolLengthLbl.setEnabled(true);
    woolLenTF.setEnabled(true);
    isLeanedLbl.setEnabled(true);
    leanedYesRB.setEnabled(true);
    leanedNoRB.setEnabled(true);

    // disable COW components
    milkYesRB.setEnabled(false);
    milkNoRB.setEnabled(false);
    isMilkingLbl.setEnabled(false);
    litProdLbl.setEnabled(false);
    litresTF.setEnabled(false);
    pregYesRB.setEnabled(false);
    pregNoRB.setEnabled(false);
    isPregnantLbl.setEnabled(false);
    isMilkingLbl.setEnabled(false);
    }//GEN-LAST:event_lambRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewAnimal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IsHealthyLbl;
    private javax.swing.ButtonGroup addAnimalBtnGroup;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTF;
    private javax.swing.ButtonGroup aliveBG;
    private javax.swing.JRadioButton aliveNoRB;
    private javax.swing.JRadioButton aliveYesRB;
    private javax.swing.JButton backAmBtn;
    private javax.swing.JLabel chickenImage;
    private javax.swing.JRadioButton chickenRB;
    private javax.swing.JLabel cowImage;
    private javax.swing.JRadioButton cowRB;
    private javax.swing.JLabel eggQtyLbl;
    private javax.swing.JTextField eggQtyTF;
    private javax.swing.JTextField eggQualTF;
    private javax.swing.JLabel eggQualityLbl;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderLbl;
    private javax.swing.ButtonGroup healthyBG;
    private javax.swing.JRadioButton healthyNoRB;
    private javax.swing.JRadioButton healthyYesRB;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel isAliveLbl;
    private javax.swing.JLabel isLayingEggsLbl;
    private javax.swing.JLabel isLeanedLbl;
    private javax.swing.JLabel isMilkingLbl;
    private javax.swing.JLabel isPregnantLbl;
    private javax.swing.JLabel lambImage;
    private javax.swing.JRadioButton lambRB;
    private javax.swing.ButtonGroup layEggsBG;
    private javax.swing.JRadioButton layEggsNoRB;
    private javax.swing.JRadioButton layEggsYesRB;
    private javax.swing.ButtonGroup leanedBG;
    private javax.swing.JRadioButton leanedNoRB;
    private javax.swing.JRadioButton leanedYesRB;
    private javax.swing.JLabel litProdLbl;
    private javax.swing.JTextField litresTF;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JRadioButton milkNoRB;
    private javax.swing.JRadioButton milkYesRB;
    private javax.swing.ButtonGroup milkingBG;
    private javax.swing.JRadioButton pregNoRB;
    private javax.swing.JRadioButton pregYesRB;
    private javax.swing.ButtonGroup pregnantBG;
    private javax.swing.JLabel title;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JTextField weightTF;
    private javax.swing.JTextField woolLenTF;
    private javax.swing.JLabel woolLengthLbl;
    // End of variables declaration//GEN-END:variables
}
