
package farmapp;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 05den
 */
public class AnimalManagementGUI extends javax.swing.JFrame {
        private ArrayList<Animal> animals = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnimalManagementGUI.class.getName());

    /**
     * Creates new form AnimalManagementGUI
     */
    public AnimalManagementGUI() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenutitle = new javax.swing.JLabel();
        viewAnimalsBtn = new javax.swing.JButton();
        addAnimalBtn = new javax.swing.JButton();
        searchAnimalBtn = new javax.swing.JButton();
        removeAnimalBtn = new javax.swing.JButton();
        backAmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(153, 255, 153));

        mainMenutitle.setBackground(new java.awt.Color(255, 255, 255));
        mainMenutitle.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mainMenutitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenutitle.setText("Animal Management");

        viewAnimalsBtn.setBackground(new java.awt.Color(254, 220, 159));
        viewAnimalsBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        viewAnimalsBtn.setText("View all Animals");
        viewAnimalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnimalsBtnActionPerformed(evt);
            }
        });

        addAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        addAnimalBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        addAnimalBtn.setText("Add");
        addAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimalBtnActionPerformed(evt);
            }
        });

        searchAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        searchAnimalBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        searchAnimalBtn.setText("Search");
        searchAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAnimalBtnActionPerformed(evt);
            }
        });

        removeAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        removeAnimalBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        removeAnimalBtn.setText("Remove");
        removeAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAnimalBtnActionPerformed(evt);
            }
        });

        backAmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmapp/images/backButton.png"))); // NOI18N
        backAmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewAnimalsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeAnimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(mainMenutitle)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mainMenutitle)
                .addGap(28, 28, 28)
                .addComponent(viewAnimalsBtn)
                .addGap(29, 29, 29)
                .addComponent(searchAnimalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(addAnimalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeAnimalBtn)
                    .addComponent(backAmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAnimalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnimalsBtnActionPerformed
        CustomMessageNoAnimals noAnimalsMsg = new CustomMessageNoAnimals();
        if (animals.isEmpty()) {
            JOptionPane.showMessageDialog(this, noAnimalsMsg);
        }
        for (Animal a : animals) {

            JOptionPane.showMessageDialog(this, a.printDetails());
        }
    }//GEN-LAST:event_viewAnimalsBtnActionPerformed

    private void searchAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAnimalBtnActionPerformed
        CustomMessageNoAnimals noAnimalsMsg = new CustomMessageNoAnimals(); 
        if (animals.isEmpty()) {
            JOptionPane.showMessageDialog(this, noAnimalsMsg);
        } else {
            int search = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter ID of animal you wish to search for: "));
            boolean isFound = false;
            for (int i = 0; i < animals.size(); i++) {
                if (animals.get(i).getId() == search) {
                    JOptionPane.showMessageDialog(this, animals.get(i).printDetails());
                    isFound = true;
                    break;
                }
            }
            if (!isFound) {
                JOptionPane.showMessageDialog(this, "Animal not found.");
            }
        }
       
    }//GEN-LAST:event_searchAnimalBtnActionPerformed

    private void addAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimalBtnActionPerformed
        
    AddNewAnimal win = new AddNewAnimal();
     win.setVisible(true);  
     this.dispose();
        
    }//GEN-LAST:event_addAnimalBtnActionPerformed

    private void removeAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAnimalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeAnimalBtnActionPerformed

    private void backAmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAmBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backAmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnimalManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnimalBtn;
    private javax.swing.JButton backAmBtn;
    private javax.swing.JLabel mainMenutitle;
    private javax.swing.JButton removeAnimalBtn;
    private javax.swing.JButton searchAnimalBtn;
    private javax.swing.JButton viewAnimalsBtn;
    // End of variables declaration//GEN-END:variables
}
