/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmapp;

import java.awt.Color;

/**
 *
 * @author 05den
 */
public class AnimalManagementGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnimalManagementGUI.class.getName());

    /**
     * Creates new form AnimalManagementGUI
     */
    public AnimalManagementGUI() {
        this.getContentPane().setBackground(new Color(255,204,153));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenutitle = new javax.swing.JLabel();
        viewAnimalsBtn = new javax.swing.JButton();
        addAnimalBtn = new javax.swing.JButton();
        searchAnimalBtn = new javax.swing.JButton();
        removeAnimalBtn = new javax.swing.JButton();
        backAmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(153, 255, 153));

        mainMenutitle.setBackground(new java.awt.Color(255, 255, 255));
        mainMenutitle.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mainMenutitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenutitle.setText("Animal Management");

        viewAnimalsBtn.setBackground(new java.awt.Color(254, 220, 159));
        viewAnimalsBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        viewAnimalsBtn.setText("View all Animals");
        viewAnimalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnimalsBtnActionPerformed(evt);
            }
        });

        addAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        addAnimalBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        addAnimalBtn.setText("Add");

        searchAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        searchAnimalBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        searchAnimalBtn.setText("Search");
        searchAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAnimalBtnActionPerformed(evt);
            }
        });

        removeAnimalBtn.setBackground(new java.awt.Color(254, 220, 159));
        removeAnimalBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeAnimalBtn.setText("Remove");

        backAmBtn.setText("Back");
        backAmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(mainMenutitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backAmBtn)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewAnimalsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(mainMenutitle)
                .addGap(32, 32, 32)
                .addComponent(viewAnimalsBtn)
                .addGap(29, 29, 29)
                .addComponent(searchAnimalBtn)
                .addGap(34, 34, 34)
                .addComponent(addAnimalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(removeAnimalBtn)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backAmBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAnimalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnimalsBtnActionPerformed

    }//GEN-LAST:event_viewAnimalsBtnActionPerformed

    private void searchAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAnimalBtnActionPerformed
       
    }//GEN-LAST:event_searchAnimalBtnActionPerformed

    private void backAmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAmBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_backAmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnimalManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnimalBtn;
    private javax.swing.JButton backAmBtn;
    private javax.swing.JLabel mainMenutitle;
    private javax.swing.JButton removeAnimalBtn;
    private javax.swing.JButton searchAnimalBtn;
    private javax.swing.JButton viewAnimalsBtn;
    // End of variables declaration//GEN-END:variables
}
