package farmapp;

import java.awt.Color;
import java.util.ArrayList;

/**
 *FarmApp.java
 * @author Denise Balasmeh, Celina Moali, Safiat dao
 *  x24701351, x23160306, x23477232  
 */

public class MainMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuGUI.class.getName());

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenutitle = new javax.swing.JLabel();
        AnimalMBtn = new javax.swing.JButton();
        productTBtn = new javax.swing.JButton();
        salesInvBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        mainMenutitle.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        mainMenutitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenutitle.setText("Main Menu");

        AnimalMBtn.setBackground(new java.awt.Color(254, 220, 159));
        AnimalMBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        AnimalMBtn.setText("Animal Management");
        AnimalMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalMBtnActionPerformed(evt);
            }
        });

        productTBtn.setBackground(new java.awt.Color(254, 220, 159));
        productTBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        productTBtn.setText("Product Tracking");
        productTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTBtnActionPerformed(evt);
            }
        });

        salesInvBtn.setBackground(new java.awt.Color(254, 220, 159));
        salesInvBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        salesInvBtn.setText("Sales & Inventory");
        salesInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesInvBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AnimalMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesInvBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenutitle))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mainMenutitle)
                .addGap(37, 37, 37)
                .addComponent(AnimalMBtn)
                .addGap(34, 34, 34)
                .addComponent(productTBtn)
                .addGap(39, 39, 39)
                .addComponent(salesInvBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnimalMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalMBtnActionPerformed
        //redirects to a different interface
        AnimalManagementGUI animalMGUI = new AnimalManagementGUI();
        animalMGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnimalMBtnActionPerformed

    private void salesInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesInvBtnActionPerformed
 
    }//GEN-LAST:event_salesInvBtnActionPerformed

    private void productTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTBtnActionPerformed
 
    }//GEN-LAST:event_productTBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnimalMBtn;
    private javax.swing.JLabel mainMenutitle;
    private javax.swing.JButton productTBtn;
    private javax.swing.JButton salesInvBtn;
    // End of variables declaration//GEN-END:variables
}
