package farmapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author safia
 */
public class ProductManagementGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductManagementGUI.class.getName());

    /**
     * Creates new form ProductManagementGUI
     */ 
    private ArrayList<ProductManagement> aList;
    private String name;
    private String expiry_date;
    private int id;
    private int quantity;
    private int count;
     // Contstructor
    public ProductManagementGUI() {
        initComponents();
        
        //Create our Array List
        aList = new ArrayList<ProductManagement>();   //NO need to put Assessment in Angle brackets <>
        // initialise our variables
        name = "";
        expiry_date = "";
        quantity = 0;
        id = 0;
        count = 0;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productManagement_label = new javax.swing.JLabel();
        viewProductsBtn = new javax.swing.JButton();
        productInventoryBtn = new javax.swing.JButton();
        updateProductBtn = new javax.swing.JButton();
        checkExpiryBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        alertBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(251, 187, 105));

        productManagement_label.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        productManagement_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productManagement_label.setText("Product Management");

        viewProductsBtn.setBackground(new java.awt.Color(254, 220, 159));
        viewProductsBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        viewProductsBtn.setText("View Products");
        viewProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductsBtnActionPerformed(evt);
            }
        });

        productInventoryBtn.setBackground(new java.awt.Color(254, 220, 159));
        productInventoryBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        productInventoryBtn.setText("Product Inventory");
        productInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInventoryBtnActionPerformed(evt);
            }
        });

        updateProductBtn.setBackground(new java.awt.Color(254, 220, 159));
        updateProductBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        updateProductBtn.setText("Update Product");
        updateProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductBtnActionPerformed(evt);
            }
        });

        checkExpiryBtn.setBackground(new java.awt.Color(254, 220, 159));
        checkExpiryBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        checkExpiryBtn.setText("Check Expiry");
        checkExpiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkExpiryBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(254, 220, 159));
        BackBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        alertBtn.setBackground(new java.awt.Color(254, 220, 159));
        alertBtn.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        alertBtn.setText("Alert");
        alertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alertBtn)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(productManagement_label)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updateProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productInventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProductsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkExpiryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(productManagement_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkExpiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String output = "";
    private void viewProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductsBtnActionPerformed
        // TODO add your handling code here:
        if(aList.isEmpty()){
            JOptionPane.showMessageDialog(null, "No products available");
        }
        for (ProductManagement p : aList){
            output += p.printDetails();
        }
        JOptionPane.showMessageDialog(null, "These are all the products");
    }//GEN-LAST:event_viewProductsBtnActionPerformed

    private void updateProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProductBtnActionPerformed

    private void alertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alertBtnActionPerformed

    private void productInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productInventoryBtnActionPerformed

    private void checkExpiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkExpiryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkExpiryBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton alertBtn;
    private javax.swing.JButton checkExpiryBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton productInventoryBtn;
    private javax.swing.JLabel productManagement_label;
    private javax.swing.JButton updateProductBtn;
    private javax.swing.JButton viewProductsBtn;
    // End of variables declaration//GEN-END:variables
}
