/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmapp;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author CelinaMoali
 */
public class SalesAndInventoryGUI extends javax.swing.JFrame {
    ArrayList<String> sales = new ArrayList<>();
    ArrayList<String> inventory = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesAndInventoryGUI.class.getName());

    /**
     * Creates new form SalesAndInventoryGUI
     */
    public SalesAndInventoryGUI() {
        this.getContentPane().setBackground(new Color(251,187,105));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenutitle = new javax.swing.JLabel();
        SalesBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        ReportBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        LogCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenutitle.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mainMenutitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenutitle.setText("Sales & Inventory");

        SalesBtn.setBackground(new java.awt.Color(254, 220, 159));
        SalesBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        SalesBtn.setText("View Sales");
        SalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesBtnActionPerformed(evt);
            }
        });
        SalesBtn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SalesBtnPropertyChange(evt);
            }
        });

        InventoryBtn.setBackground(new java.awt.Color(254, 220, 159));
        InventoryBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        InventoryBtn.setText("View Inventory");
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });

        ReportBtn.setBackground(new java.awt.Color(254, 220, 159));
        ReportBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReportBtn.setText("Create Report");
        ReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(254, 220, 159));
        BackBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        LogCombo.setBackground(new java.awt.Color(254, 220, 159));
        LogCombo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LogCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select:", "log sales", "log inventory" }));
        LogCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReportBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addComponent(mainMenutitle)
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(LogCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mainMenutitle)
                .addGap(34, 34, 34)
                .addComponent(SalesBtn)
                .addGap(28, 28, 28)
                .addComponent(InventoryBtn)
                .addGap(28, 28, 28)
                .addComponent(LogCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportBtn)
                    .addComponent(BackBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesBtnActionPerformed
        if(sales.isEmpty()){
            JOptionPane.showMessageDialog(this, "No sales logged");
        }
        else{
            JOptionPane.showMessageDialog(this, "sales logs:\n" + String.join("\n", sales));
        }
    }//GEN-LAST:event_SalesBtnActionPerformed

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        if(inventory.isEmpty()){
            JOptionPane.showMessageDialog(this, "No inventory logged");
        }
        else{
            JOptionPane.showMessageDialog(this, "inventory logs:\n" + String.join("\n", inventory));
        }   
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void ReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBtnActionPerformed
        
    }//GEN-LAST:event_ReportBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void LogComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogComboActionPerformed
        String choice = LogCombo.getSelectedItem().toString();
        
        if(choice.equals("log sales")){
            String sale = JOptionPane.showInputDialog(this,"Enter Sale Details:");
            if(sale != null && !sale.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sale logged");
                sales.add(sale);
         }
        }
        else if(choice.equals("log inventory")){
            String item = JOptionPane.showInputDialog(this, "Enter Inventory Item:");
            if(item != null && !item.isEmpty()){
                JOptionPane.showMessageDialog(this, "Inventory Logged");
                inventory.add(item);
            }
        }   
    }//GEN-LAST:event_LogComboActionPerformed

    private void SalesBtnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SalesBtnPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_SalesBtnPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesAndInventoryGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JComboBox<String> LogCombo;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JButton SalesBtn;
    private javax.swing.JLabel mainMenutitle;
    // End of variables declaration//GEN-END:variables
}
